name: tako_play
description: A new Flutter project.

publish_to: "none"

version: 1.4.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  better_player: ^0.0.81
  cached_network_image: ^3.1.0+1
  chopper: ^4.0.5
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  get: ^4.6.0
  google_fonts: ^2.3.1
  html: ^0.15.0
  logging: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  flutter_staggered_animations: ^1.0.0
  sqflite: ^2.0.2
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0d1321"
  image: assets/images/splash.png

  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
