name: tako_play
description: A new Flutter project.

publish_to: "none"

version: 1.6.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  aespack: ^0.0.3
  better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057
  cached_network_image: ^3.1.0+1
  chopper: ^6.1.4
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  # html: ^0.15.0
  logging: ^1.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  sqflite: ^2.3.0
  url_launcher: ^6.1.12
  uuid: ^3.0.6
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0d1321"
  image: assets/images/splash.png

  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
